dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - coverage run --source=datapackage_to_datasette ./run_tests.py
  - isort --profile black -c --diff .
  - flake8 .
  - black --check .
  - poetry build
after_success:
  - coveralls
